apiVersion: v1
kind: Namespace
metadata:
  name: gitlab
  labels:
    name: gitlab
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: gitlab
  name: gitlab-config
  annotations:
    "volume.beta.kubernetes.io/storage-class": "nfs"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10M
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: gitlab
  name: gitlab-data
  annotations:
    "volume.beta.kubernetes.io/storage-class": "nfs"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: gitlab
  name: gitlab-log
  annotations:
    "volume.beta.kubernetes.io/storage-class": "nfs"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---

apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: gitlab
  name: gitlab
  labels:
    app: gitlab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitlab
  template:
    metadata:
      labels:
        app: gitlab
    spec:
      volumes:
      - name: hostvolume
        hostPath:
          path: /tmp/gitlab
          type: DirectoryOrCreate
      hostname: gitlab
      containers:
      - name: gitlab
        image: gitlab/gitlab-ce:latest
        volumeMounts:
        - mountPath: /etc/gitlab
          subPath: config
          name: gitlab-config
        - mountPath: /var/log/gitlab
          subPath: logs
          name: gitlab-log
        - mountPath: /var/opt/gitlab/data
          name: gitlab-data
      volumes:
      - name: gitlab-config
        persistentVolumeClaim:
          claimName: gitlab-config
      - name: gitlab-data
        persistentVolumeClaim:
          claimName: gitlab-data
      - name: gitlab-log
        persistentVolumeClaim:
          claimName: gitlab-log
---

apiVersion: v1
kind: Service
metadata:
  namespace: gitlab
  name: gitlab
  labels:
    app: gitlab
spec:
  selector:
    app: gitlab
  ports:
  - name: http
    port: 80
    targetPort: 80
  - name: https
    port: 443
    targetPort: 443
  - name: ssh
    port: 22
    targetPort: 22

